
/*

Object:  	Database [DBAdmin_QA]    
Date: 		2016-01-24
Author: 	Charlton Julius
Notes: 		Alter Below as necessary for your environment

*/

USE [master]
GO

CREATE DATABASE [DBAdmin_QA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBAdmin_QA', FILENAME = N'D:\DB\DBAdmin_QA.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DBAdmin_QA_log', FILENAME = N'D:\DB\DBAdmin_QA_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DBAdmin_QA] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBAdmin_QA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBAdmin_QA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBAdmin_QA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBAdmin_QA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBAdmin_QA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBAdmin_QA] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBAdmin_QA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBAdmin_QA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBAdmin_QA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBAdmin_QA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBAdmin_QA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBAdmin_QA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBAdmin_QA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBAdmin_QA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBAdmin_QA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBAdmin_QA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBAdmin_QA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBAdmin_QA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBAdmin_QA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBAdmin_QA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBAdmin_QA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBAdmin_QA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBAdmin_QA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBAdmin_QA] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DBAdmin_QA] SET  MULTI_USER 
GO

ALTER DATABASE [DBAdmin_QA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBAdmin_QA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBAdmin_QA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBAdmin_QA] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DBAdmin_QA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBAdmin_QA] SET  READ_WRITE 
GO


