-- All US States & Territories with Full name and postal code abbreviation
-- T-SQL Code

 CREATE TABLE dbo.States_Postal ( [State] VARCHAR(50), [Postal] VARCHAR(5));
 GO
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Alabama','AL');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Alaska','AK');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('American Samoa','AS');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Arizona','AZ');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Arkansas','AR');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('California','CA');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Colorado','CO');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Connecticut','CT');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Delaware','DE');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Dist. of Columbia','DC');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Florida','FL');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Georgia','GA');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Guam','GU');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Hawaii','HI');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Idaho','ID');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Illinois','IL');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Indiana','IN');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Iowa','IA');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Kansas','KS');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Kentucky','KY');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Louisiana','LA');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Maine','ME');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Maryland','MD');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Marshall Islands','MH');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Massachusetts','MA');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Michigan','MI');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Micronesia','FM');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Minnesota','MN');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Mississippi','MS');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Missouri','MO');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Montana','MT');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Nebraska','NE');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Nevada','NV');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('New Hampshire','NH');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('New Jersey','NJ');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('New Mexico','NM');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('New York','NY');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('North Carolina','NC');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('North Dakota','ND');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Northern Marianas','MP');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Ohio','OH');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Oklahoma','OK');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Oregon','OR');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Palau','PW');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Pennsylvania','PA');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Puerto Rico','PR');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Rhode Island','RI');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('South Carolina','SC');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('South Dakota','SD');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Tennessee','TN');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Texas','TX');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Utah','UT');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Vermont','VT');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Virginia','VA');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Virgin Islands','VI');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Washington','WA');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('West Virginia','WV');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Wisconsin','WI');
INSERT INTO dbo.States_Postal([State],[Postal]) VALUES('Wyoming','WY');
